[variables]
PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn wsgi:app"